version: '2'

services:
  gitbook:
    image: altus5/gitbook
    volumes:
      - ..:/gitbook
      - gitbook_node_modules:/gitbook/node_modules
    ports:
      - 4000:4000

volumes:
  gitbook_node_modules:
    driver: local
